spring:
  application:
    name:  ribbon-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true

server:
  port : 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/
  instance:
    #服务实例元数据，设置实例名，区分同一服务中不同实例的唯一标识
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
     #启用注册IP
    prefer-ip-address: true

hello-service:
  ribbon:
    ConnectTimeout: 2000
    ReadTimeout: 2000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1


management:
  endpoints:
    web:
      exposure:
        include: "*"
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000